app:
  bot:
    name: SszRulesBot
    token: 6878454405:AAH6Mt6CaZ9-mXKE3bLD3oVQmEtRhaJP6MU
    admins: 782243896
    right-answers: 3
    limit-answers: 5
    test-enable: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rules?currentSchema=rules
    username: postgres
    password: postgres
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yaml
    default-schema: rules

preliquibase:
  sqlScriptReferences: classpath:db/changelog/schema/SCHEMA.sql
  enabled: false